arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - bravo_axis_g
    - bravo_axis_f
    - bravo_axis_e
    - bravo_axis_d
    - bravo_axis_c
    - bravo_axis_b
  gains:
    bravo_axis_g:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bravo_axis_f:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bravo_axis_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bravo_axis_d:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bravo_axis_c:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bravo_axis_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1