controller_list:
  - name: fake_tail_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - tail_axis_1
      - tail_axis_2
      - tail_axis_3
initial:  # Define initial robot poses per group
  - group: tail_arm
    pose: home