arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - tail_axis_1
    - tail_axis_2
    - tail_axis_3
  gains:
    tail_axis_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tail_axis_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    tail_axis_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1