controller_list:
  - name: fake_r5m_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    joints:
      - joint5
      - joint6
initial:
  - group: r5m_joints
    pose: stow      
